@startuml classes_real

title Real Sub-Classing Structure of the Module introspection_lib.base_exception

class Exception <<Builtin>>

class TypeError <<Builtin>>

class ValueError <<Builtin>>

class AttributeError <<Builtin>>

class LookupError <<Builtin>>

Exception <|-- TypeError

Exception <|-- ValueError

Exception <|-- AttributeError

Exception <|-- LookupError

class IndexError <<Builtin>>

class KeyError <<Builtin>>

LookupError <|-- IndexError

LookupError <|-- KeyError

class UT_Exception

Exception <|- UT_Exception

class UT_TypeError

TypeError <|-- UT_TypeError

class UT_ValueError

ValueError <|-- UT_ValueError

class UT_AttributeError

AttributeError <|-- UT_AttributeError

class UT_IndexError

IndexError <|-- UT_IndexError

class UT_KeyError

KeyError <|-- UT_KeyError

@enduml