!$BASE_EXCEPTIONS_EXCEPTION = "v2"

!if %not(%variable_exists("$CLASSES"))
    !include ../Templates/Classes2.cuml
!endif

class Exception <<Builtin>> {
    + {field} args: tuple(type A)
    + __traceback__ : types.TracebackType
    + with_traceback(): type.TracebackType -> Exception
    + __init__(): type A -> None
}