!define BASE_EXCEPTIONS_EXCEPTION

!ifndef CLASSES
!include ../Templates/Classes.cuml
!endif

class Exception <<Builtin>> {
    + {field} args: tuple(type A)
    + __traceback__ : types.TracebackType
    + with_traceback(): type.TracebackType -> Exception
    + __init__(): type A -> None
}