@startuml ut_exception

title Class Diagram of introspection_lib.base_exceptions.UT_Exception Class

!if %not(%variable_exists("$CLASSES"))
    !include ../Templates/Classes2.cuml
!endif

namespace builtins {
    !if $is_not_defined("$BASE_EXCEPTIONS_EXCEPTION")
        !include ./exception.iuml
    !endif
}

namespace traceback {
    !if $is_not_defined("$TRACEBACK_EXCEPTIONTRACEBACK")
        !include ../traceback/ExceptionTraceback.iuml
    !endif

    !if $is_not_defined("$TRACEBACK_STACKTRACEBACK")
        !include ../traceback/StackTraceback.iuml
    !endif

    ExceptionTraceback --|> StackTraceback
}

class UT_Exception {
    __
    + __init__(Message, SkipFrames = None, FromTraceback = None):
    str/, int OR None, type.TracebackType OR None/ -> None
}

builtins.Exception <|--- UT_Exception

!if $is_not_defined("$BASE_EXCEPTION_TRACEBACK_PLUGIN")
    !include ./traceback_plugin.iuml
!endif

TracebackPlugin <|-- UT_Exception

TracebackPlugin o--- traceback.ExceptionTraceback

builtins.Exception <.. TracebackPlugin : overrides

@enduml