@startuml logger_filter

title Activity Diagram of the Logger Filter

start

:Message: logging.LogRecord<

if (Message level is within allowed by\nthe logger console ouput range AND\n>= logger's threshold level?) then (yes)
    :set console output flag of\nMessage to True;
else (No)
    :set console output flag of\nMessage to False;
endif

if (Message level is within allowed by\nthe logger propagation range AND\n>= logger's threshold level?) then (yes)
    :set propagation flag of\nMessage to True;
else (No)
    :set propagation flag of\nMessage to False;
endif

:return True>

stop

@enduml