@startuml components

title Components Diagram of the Library introspection_lib

!if %not(%variable_exists("$COMPONENTS"))
    !include ./Templates/Components2.cuml
!endif

$library(introspection_lib) {
    !if $is_not_defined("$BASE_EXCEPTIONS_COMPONENTS")
        !include ./base_exceptions/base_exceptions_components.iuml
    !endif
    
    !if $is_not_defined("$TRACEBACK_COMPONENTS")
        !include ./traceback/traceback_components.iuml
    !endif
    
    ExceptionTraceback -o CustomExceptions
    
    !if $is_not_defined("$LOGGING_COMPONENTS")
        !include ./logging/logging_components.iuml
    !endif
    
    StackTraceback -[hidden]- DummyLogger

    !if $is_not_defined("$DYNAMIC_IMPORT")
     !include ./dynamic_import/dynamic_import_module.iuml
    !endif

    CustomExceptions <-- import_from_module
    CustomExceptions <-- import_module
}

@enduml