!define TRACEBACK_EXCEPTIONTRACEBACK

!ifndef CLASSES
!include ../Templates/Classes.cuml
!endif

class ExceptionTraceback {
    ___
    ..special methods..
    + _ _init_ _(SkipFrames = None, ContextLength = None, ConsoleWidth = None, Traceback = None) : /int, int, int, types.TracebackType/ -> None
}