!define TRACEBACK_STACKTRACEBACK

!ifndef CLASSES
!include ../Templates/Classes.cuml
!endif

class StackTraceback {
    ..class attributes..
    + static_field(ContextLength) : int = 3
    ..instance attributes..
    + ConsoleWidth : int = 80
    ..read-only properties..
    # {field} CallChain : list(str)
    # Info : str
    ..'private' instance attributes..
    - {field} _lstTraceback: list(tuple(str, str, str, int >= 0, int >= 0, list(str)))
    ___
    ..special methods..
    + _ _init_ _(SkipFrames = None, ContextLength = None, ConsoleWidth = None) : /int, int, int/ -> None
    + _ _del_ _() : None -> None
}