!define TRACEBACK_COMPONENTS

!ifndef COMPONENTS
!include ../Templates/Components.cuml
!endif

module(traceback) {
    function(ParseFramesList)

    class(StackTraceback)
    
    class(ExceptionTraceback)
    
    ParseFramesList <-- StackTraceback

    StackTraceback <|- ExceptionTraceback
}