@startuml check_if_source_file

title Activity Diagram of the function IsPyFile()

start

:<b>Path</b> - str, expected path to a file<

if (<b>Path</b> is not a string?) then (Yes)
    :raise TypeError (sub-) class exception;
    
    end
else (No)
    if (<b>Path</b> is a file and not a symlink?) then (True)
        if (<b>Path</b> ends with '.py'?) then (Yes)
            :return True>
        else (No)
            :return False>
        endif
    else (False)
        :return False>
    endif
endif

stop

@enduml